### ISSUE TITLE
on line 67 or 68's selector it missing a comma.

### ISSUE THREAD

**Issue by TheTechRobo** [csourcesc/old-scratch-blue#3]
I got this warning with stylus

**Comment by moeenio** [comment]
https://github.com/csourcesc/old-scratch-blue/blob/164abaf0a1e21e80377e63f1915ac0cf6450154d/old-scratch-blue.user.css#L67 right, mind fixing it @TheTechRobo ?

**Comment by TheTechRobo** [comment]
sure, I'll do it right now.
